# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mr. Baker's Lessons
email: cbaker@jpgacademy.org
description: > # this means to ignore newlines until "baseurl:"
  This will hold the lesson plans of Mr. Baker.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://baker.jpgapps.org" # the base hostname & protocol for your site
github_username:  malacon

collections:
  - physics

# Build settings
markdown: kramdown
